global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true

log:
  level: INFO

accessLog: {}

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: velonia_network

  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: contato@velonia.com.br
      storage: /letsencrypt/acme.json

      httpChallenge:
        entryPoint: web
