BEGIN;

ALTER TABLE catalogo.produtos

ADD COLUMN IF NOT EXISTS codigo_oem VARCHAR(120),

ADD COLUMN IF NOT EXISTS codigo_original VARCHAR(120),

ADD COLUMN IF NOT EXISTS subcategoria VARCHAR(150),

ADD COLUMN IF NOT EXISTS cest VARCHAR(20),

ADD COLUMN IF NOT EXISTS origem VARCHAR(80),

ADD COLUMN IF NOT EXISTS garantia_meses INTEGER,

ADD COLUMN IF NOT EXISTS comprimento_cm NUMERIC(10,2),

ADD COLUMN IF NOT EXISTS largura_cm NUMERIC(10,2),

ADD COLUMN IF NOT EXISTS altura_cm NUMERIC(10,2),

ADD COLUMN IF NOT EXISTS volume_m3 NUMERIC(10,4);

COMMIT;
